### PR TITLE
Remove nest-asyncio

### PR DESCRIPTION
**Pull request by davidbrochart**
Experimenting with jupyter-client's [run_sync](https://github.com/jupyter/jupyter_client/blob/76a0f575d1e47b28f017a909df9c5b696a8207e8/jupyter_client/utils.py#L51) which doesn't use `nest-asyncio`.

### CODE REVIEW

**Comment by davidbrochart** [comment]
cc @maartenbreddels @SylvainCorlay

**Comment by blink1073** [comment]
I'm hesitant to add a whole new library.  Perhaps we could put the code in Jupyter Core 5.x and 4.x?

**Comment by davidbrochart** [comment]
Definitely not a new library just for this. Actually, it may also be fine like that, even though there's a bit of code duplication.

**Comment by blink1073** [comment]
`jupyter_client` could depend on `jupyter_core` once it is there.

**Comment by davidbrochart** [comment]
OK, I'll open PRs.

**Comment by blink1073** [comment]
We should be able to use meeseeks to backport the PR from main.

**Comment by davidbrochart** [comment]
This PR needs https://github.com/jupyter/jupyter_core/pull/315.

**Comment by davidbrochart** [comment]
https://github.com/jupyter/nbclient/pull/259/commits/b77eb065e3db8bf7e1fa93d975b2d3e29cc68aab reapplies #258, which was overridden by #257.

**Comment by blink1073** [comment]
We shouldn't per-emptively add upper bounds to dependencies, see https://iscinumpy.dev/post/bound-version-constraints/

**Comment by davidbrochart** [comment]
> We shouldn't per-emptively add upper bounds to dependencies, see https://iscinumpy.dev/post/bound-version-constraints/

:+1:

**Pull request merged**
