### PR TITLE
Drop Travis CI

### LINKED ISSUE #123: Dropping Travis CI
Should we get rid of Travis CI, now that we use GitHub Actions?

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #123

### CODE REVIEW

**Comment by choldgraf** [comment]
just to confirm, our GHA suite covers all of the same tests and functionality as the travis one, right? I think so but we should probably confirm

**Comment by davidbrochart** [comment]
I think so. I just added python 3.9 and re-enabled windows for all python versions, just to see if it still fails.

**Comment by davidbrochart** [comment]
I disabled windows for python 3.8 and 3.9 again, as they are failing and I'm not sure why.

**Review by willingc — APPROVED** [review]
Thanks @davidbrochart. I'm going to merge this and we can resolve what is up with windows 3.8 and 3.9 in another PR.

**Comment by choldgraf** [comment]
👋 bye travis!

**Pull request merged**
