### PR TITLE
[WIP] Run coroutines in another thread for blocking API

### PR DESCRIPTION
**Pull request by davidbrochart**
Trying to get rid of nest_asyncio (see https://github.com/nteract/papermill/issues/490).

### CODE REVIEW

**Comment by davidbrochart** [comment]
@MSeal this seems like the deadlock issue you were mentioning, `test_many_parallel_notebooks` hangs and it is the test which does multiprocessing.

**Comment by MSeal** [comment]
Yep -- this is basically guaranteed with os threading ontop of forking at the same time because, among other reasons, the os replicates thread local context that's invalid.

**Comment by MSeal** [comment]
Is there anyway we can apply or not apply nest_asyncio and catch the exception to switch modes automatically instead of introducing more concurrent patterns in-place?

**Comment by davidbrochart** [comment]
Yes, we can try without nest_asyncio and if we catch the exception try again with it. Thanks, I'll open a PR.

**Pull request closed without merging**
