### PR TITLE
Use GH actions to test on OSX and Windows as well

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Some interesting results: https://github.com/davidbrochart/nbclient/pull/1

**Comment by choldgraf** [comment]
Haha whoa - I wonder why it isn't running on this PR though?

**Comment by davidbrochart** [comment]
Yes I don't know why either. And it doesn't run the `coverage` job.

**Comment by choldgraf** [comment]
what if you manually set it to `on: pull_request, push`? Maybe it's the `*` that is the issue?

**Comment by davidbrochart** [comment]
Ah it needs the tests to pass before doing code coverage :smile:

**Comment by davidbrochart** [comment]
`test_many_parallel_notebooks` was failing because it uses multiprocessing (a pool of 2 cores +  the main python program). Maybe we only have one core on GH actions?

**Comment by davidbrochart** [comment]
This is ready to be merged. We are keeping Travis CI anyway, so it's just adding GitHub actions CI, except that we don't use `pebble` anymore for `test_many_parallel_notebooks` (for some reason it didn't work on GH actions, and we have the same with `concurrent.futures.ProcessPoolExecutor`).

**Pull request merged**
