### PR TITLE
Fixing AttributeError when kernel cleanup occurs before the kernel is created.

### PR DESCRIPTION
**Pull request by golf-player**

### CODE REVIEW

**Comment by golf-player** [comment]
I put the check in execute since it's only the first one causing problems. In other cases where kernel cleanup is called and fails because kernel_manager is not defined, it's probably best to fail since something is very wrong

**Comment by davidbrochart** [comment]
LGTM.

**Comment by davidbrochart** [comment]
Thanks!

**Comment by golf-player** [comment]
Appreciate the quick response. Thanks!

**Pull request merged**
