### PR TITLE
Remove references to Executor

### PR DESCRIPTION
**Pull request by takluyver**
I guess this was a possible name for the class at one point, but it's called NotebookClient now.

### CODE REVIEW

**Comment by davidbrochart** [comment]
Thanks @takluyver.
Not sure what is happening in the docs build. Maybe it is caused by our move to GitHub actions @choldgraf?

**Comment by choldgraf** [comment]
hmmm - that's weird, do you know who runs the ReadTheDocs? I think we can probably disable CircleCI and just use that for docs previewing.

**Comment by davidbrochart** [comment]
I am one of the maintainers of the nbclient RTD account. Is there something you want me to do there?

**Comment by takluyver** [comment]
At an educated guess, @choldgraf is suggesting enabling RTD builds for pull requests :-)

https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

**Comment by davidbrochart** [comment]
Thanks, it's done!

**Comment by takluyver** [comment]
OK, let's see if a close/reopen makes it run.

**Comment by takluyver** [comment]
Well, the CI [worked](https://readthedocs.org/projects/nbclient/builds/12524523/), but the build failed with the same error. How do you want to handle that? Fix the error separately and then come back to this PR?

**Comment by davidbrochart** [comment]
Do you mind applying @choldgraf's change in this PR @takluyver?

**Comment by takluyver** [comment]
https://nbclient--127.org.readthedocs.build/en/127/index.html :+1:

**Comment by davidbrochart** [comment]
Awesome, thanks!

**Pull request merged**
